version: '3.9'
services:
  app:
    build:
      context: .
    ports:
      - 1025:25
    volumes:
      - ./spool:/var/spool/smtp-hook/
    environment:
      - DOMAIN=${DOMAIN}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - MAX_MESSAGE_SIZE=${MAX_MESSAGE_SIZE}
      - LOG_LEVEL=${LOG_LEVEL}
      - ALLOWED_DOMAINS=${ALLOWED_DOMAINS}
