version: '3.9'
services:
  app:
    build:
      context: .
    ports:
      - 1025:1025
    volumes:
      - .:/app
    environment:
      - DOMAIN=${DOMAIN}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - MAX_MESSAGE_SIZE=${MAX_MESSAGE_SIZE}
